CC = g++ -Wall
SOURCE = zchaff64/mengdongqi.cpp zchaff64/mengdongqi.h zchaff64/SAT.h \
	    zchaff_utils.cpp \
	    zchaff_solver.cpp\
	    zchaff_base.cpp \
	    zchaff_dbase.cpp \
	    zchaff_c_wrapper.cpp \
	    zchaff_cpp_wrapper.cpp \
CC 
